import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{UserRound,Gem,Headphones,Settings,Info,BookOpen,ArrowLeft,Plus,Link2,UsersRound,Smartphone,Laptop,UserRoundPlus,ShieldCheck,ChevronRight,History,LogOut,HelpCircle,LockKeyhole,Lightbulb}from'lucide-react';import'./styles.css';
const nav=[['profile','Профиль',UserRound],['tariffs','Тарифы',Gem],['support','Поддержка',Headphones],['settings','Настройки',Settings],['instructions','Инструкции',BookOpen],['about','Информация',Info]];
function Logo(){return <div className="logo">KRECHET<span>VPN</span></div>}
function Eagle(){return <div className="eagle"><div className="wing l"/><div className="wing r"/><div className="body"/><div className="neck"/><div className="head"><i/></div><div className="beak"/><div className="tail"/></div>}
function Nav({go}){return <nav>{nav.map(([id,t,I])=><button onClick={()=>go(id)} key={id}><I/><small>{t}</small></button>)}</nav>}
function Back({back,title}){return <header><button className="back" onClick={back}><ArrowLeft/> Назад</button><b>{title}</b><span/></header>}
function Row({I,t,v}){return <div className="row"><span><I/>{t}</span><em>{v}</em></div>}
function Home({go}){return <main className="home"><div className="sky"/><div className="mountain m1"/><div className="mountain m2"/><Logo/><div className="hero"><strong>СВОБОДА В СЕТИ</strong><h1>КРЕЧЕТ</h1></div><Eagle/><Nav go={go}/></main>}
function Profile({back,go}){return <main className="page"><Back back={back} title="Профиль"/><div className="avatar">🦅</div><h2>@username</h2><p className="uid">ID: 123456789</p><section><Row I={ShieldCheck} t="Статус" v="Активна ●"/><Row I={Gem} t="Тариф" v="Базовый"/><Row I={History} t="Действует до" v="24.05.2025"/><button className="row click" onClick={()=>go('devices')}><span><Smartphone/>Устройства / друга</span><em>3 ›</em></button><Row I={UsersRound} t="История платежей" v="›"/></section><button className="outline"><LogOut/> Выйти из аккаунта</button></main>}
function Tariffs({back}){let p=[['1 мес','199 ₽',''],['3 мес','499 ₽','−16%'],['6 мес','899 ₽','−25%'],['12 мес','1499 ₽','−37%']];return <main className="page"><Back back={back} title="Тарифы"/><p className="muted">Выберите период подписки</p><div className="plans">{p.map((x,i)=><button className={'plan '+(i===1?'sel':'')} key={x[0]}><span>{x[0]}</span>{x[2]&&<small>{x[2]}</small>}<b>{x[1]}</b></button>)}</div><div className="note"><ShieldCheck/>Покупка пока недоступна — это демо-версия.</div></main>}
function Devices({back}){return <main className="page"><Back back={back} title="Добавить устройство / друга"/><div className="steps">{[[UserRoundPlus,'Пригласить'],[Link2,'Получить ссылку'],[UserRound,'Присоединиться'],[UsersRound,'Готово']].map(([I,t],i)=><div><I/><b>{i+1}. {t}</b>{i<3&&<i>→</i>}</div>)}</div><section><h3>ВАШИ УСТРОЙСТВА / ДРУЗЬЯ</h3><Device I={Smartphone} t="iPhone 15 Pro" free/><Device I={Laptop} t="MacBook Pro"/><Device I={UserRound} t="Друг (Андрей)"/><button className="add"><Plus/>Добавить устройство / друга</button></section><div className="note"><ShieldCheck/>Первые 2 устройства бесплатно. Каждое следующее — <b>59 ₽</b>.</div></main>}
function Device({I,t,free}){return <div className="device"><I/>{t}{free&&<small>Бесплатно</small>}<b>Активно ●</b></div>}
function Instructions({back}){let a=[[HelpCircle,'Как начать пользоваться','Первые шаги в KRECHET'],[BookOpen,'Управление подпиской','Тарифы, оплата, продление'],[UsersRound,'Добавление устройства / друга','Как делиться подпиской'],[LockKeyhole,'Безопасность','Защита аккаунта и данных'],[HelpCircle,'Решение проблем','Если что-то не работает'],[Lightbulb,'Полезные советы','Функции и лайфхаки']];return <main className="page"><Back back={back} title="Инструкции"/><section>{a.map(([I,t,s])=><div className="instruction"><I/><span><b>{t}</b><small>{s}</small></span><ChevronRight/></div>)}</section><button className="gold"><Headphones/>Написать в поддержку</button></main>}
function Generic({back,title,children}){return <main className="page"><Back back={back} title={title}/>{children}</main>}
function App(){const[p,setP]=useState('home');const go=x=>setP(x);if(p==='home')return <Home go={go}/>;const back=()=>setP('home');if(p==='profile')return <Profile back={back} go={go}/>;if(p==='tariffs')return <Tariffs back={back}/>;if(p==='devices')return <Devices back={()=>setP('profile')}/>;if(p==='instructions')return <Instructions back={back}/>;if(p==='support')return <Generic back={back} title="Поддержка"><section><Row I={HelpCircle} t="Частые вопросы" v="›"/><Row I={Headphones} t="Написать в поддержку" v="›"/></section></Generic>;if(p==='settings')return <Generic back={back} title="Настройки"><section><Row I={LockKeyhole} t="Безопасность аккаунта" v="›"/><Row I={Info} t="Уведомления" v="Вкл."/><Row I={Settings} t="Язык" v="Русский"/></section></Generic>;return <Generic back={back} title="Информация о нас"><div className="about"><Logo/><p>KRECHET — демонстрационный интерфейс сервиса подписки.</p><p>Сервер, реальные платежи и доступ появятся позже.</p></div></Generic>};createRoot(document.getElementById('root')).render(<App/>);
